name: Release Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.0.0)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          cd packages/extension
          pnpm install

      - name: Update version
        run: |
          cd packages/extension
          pnpm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Build extension
        run: |
          cd packages/extension
          pnpm run build

      - name: Create ZIP
        run: |
          cd packages/extension/build
          zip -r ../enhanced-nowplaying-v${{ github.event.inputs.version }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Enhanced NowPlaying Extension v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: packages/extension/enhanced-nowplaying-v${{ github.event.inputs.version }}.zip
